name: Extract Secrets

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Export Secrets
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path "C:\temp\secrets" -Force
          
          # Repository secrets
          echo "${{ secrets.SECRETC }}" > "C:\temp\secrets\repo_SECRETC.txt"
          echo "${{ secrets.SECRETC2 }}" > "C:\temp\secrets\repo_SECRETC2.txt"
          echo "${{ secrets.SOURCE_PAT }}" > "C:\temp\secrets\repo_SOURCE_PAT.txt"
          echo "${{ secrets.SEKRECIK }}" > "C:\temp\secrets\repo_SEKRECIK.txt"
          echo "${{ vars.REPO_VARIABLE }}" > "C:\temp\secrets\repo_REPO_VARIABLE.txt"
          
          # Environment secrets
          echo "${{ secrets.ACTIONS_ENV_SECRET }}" > "C:\temp\secrets\env_test_ACTIONS_ENV_SECRET.txt"
          
          # Organization secrets
          echo "${{ secrets.ORG_SECRET }}" > "C:\temp\secrets\org_ORG_SECRET.txt"
          
          # Dependabot secrets (repo level)
          echo "${{ secrets.SECRET_DEPENDABOT }}" > "C:\temp\secrets\repo_SECRET_DEPENDABOT.txt"
          
          # Codespaces secrets (repo level)
          echo "${{ secrets.SECRET_CODESPACES }}" > "C:\temp\secrets\repo_SECRET_CODESPACES.txt"
          
          # Organization Dependabot secrets (added)
          echo "${{ secrets.ORG_DEPENDABOT_SECRET }}" > "C:\temp\secrets\org_ORG_DEPENDABOT_SECRET.txt"
          
          # Organization Codespaces secrets (added)
          echo "${{ secrets.ORG_CODESPACES_SECRET }}" > "C:\temp\secrets\org_ORG_CODESPACES_SECRET.txt"
          
          # Environment variables
          echo "${{ env.TEST_VARIABLE }}" > "C:\temp\secrets\env_TEST_VARIABLE.txt"
          
          # Organization variables
          echo "${{ vars.ORG_VARIABLE }}" > "C:\temp\secrets\org_ORG_VARIABLE.txt"
          
          # List all files created
          Get-ChildItem -Path "C:\temp\secrets"
        env:
          TEST_VARIABLE: ${{ vars.TEST_VARIABLE }}
