name: "Migrate Variables & Secrets"

on:
  workflow_dispatch:
    inputs:
      source_org:
        description: 'Source organization'
        required: true
      source_repo:
        description: 'Source repository (leave empty to migrate all)'
        required: false
      target_org:
        description: 'Target organization'
        required: true
      target_repo:
        description: 'Target repository'
        required: true
      scope:
        description: 'Comma-separated scope: repo,env,codespaces,dependabot,secrets'
        required: true
      force:
        description: 'Overwrite existing values?'
        required: false
        default: 'false'
      dry_run:
        description: 'Dry run without changes'
        required: false
        default: 'true'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run Migration Script
 
        run: |
         pwsh -NoLogo -NoProfile -ExecutionPolicy Bypass -File migration/Migrate-GitHubVariables.ps1 \
         -SourceOrg "${{ github.event.inputs.source_org }}" \
         -SourceRepo "${{ github.event.inputs.source_repo }}" \
         -TargetOrg "${{ github.event.inputs.target_org }}" \
         -TargetRepo "${{ github.event.inputs.target_repo }}" \
         -SourcePAT "${{ secrets.SOURCE_PAT }}" \
         -TargetPAT "${{ secrets.TARGET_PAT }}" \
         -Scope "${{ github.event.inputs.scope }}" \
         $( [ "${{ github.event.inputs.force }}" == 'true' ] && echo "-Force" ) \
